services:
  neo4j:
    build: ./neo4j
    ports:
      - "7473:7473"
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/your_password"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      # NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,neo4j-graph-data*.*"  # Added GDS procedures
      NEO4J_PLUGINS: '["graph-data-science"]'  # Enable GDS plugin

    volumes:
      - ./data:/data

